### ISSUE TITLE
pigx init?

### ISSUE THREAD

**Issue by jonathanronen** [BIMSBbioinfo/pigx_docs#3]
@rekado once mentioned an idea to help users get started by providing an `--init` argument to the cli, which would iirc copy the settings file and sample sheet from the example into the users' current directory.

The RNAseq documentation currently mentions this, although i'm not sure it's true. Specifically, it mentions

```bash
pigx rnaseq --init
```

which might not even be a smart way of implementing this feature.

This should be standardized in all pipelines and corresponding documentation. If we implement it. Have we? Should we?
@rekado @Blosberg @borauyar @alexg9010 @katwre @frenkiboy @al2na

**Comment by rekado** [comment]
We haven't but we should.

I wasn't sure about the CLI: we need to init both the sample sheet and the settings file. Should `--init` take an argument?  Should it assume both sample sheet and settings file initialisation if no argument is given?  Or should we provide `--init-sample-sheet` and `--init-settings`?

The implementation is trivial.

**Comment by jonathanronen** [comment]
How about `--init` for both, and also `--init-{sample-sheet,settings}` for each separately? Is that just confusing?

**Comment by rekado** [comment]
I think that's worse than `--init[=(sample-sheet|settings)]`, i.e. `--init` alone DWIM (create sample sheet if none exists, and creates a settings file if none exists), whereas `--init=sample-sheet` generates a sample sheet template and `--init=settings` generates a settings file template.

**Comment by rekado** [comment]
This is now implemented in all pipelines.
